name: CI

on: [push, pull_request]

jobs:
  flatpak-builder:
    name: Flatpak Builder
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/elementary/flatpak-platform/runtime:6
      options: --privileged
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build
        uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v3
        with:
          bundle: com.github.matthiasjg.trimirjournal.flatpak
          manifest-path: com.github.matthiasjg.trimirjournal.yml
          # run-tests: true
          repository-name: appcenter
          repository-url: https://flatpak.elementary.io/repo.flatpakrepo
          cache-key: "flatpak-builder-${{ github.sha }}-${{ hashFiles('com.github.matthiasjg.trimirjournal.yml') }}"
          
  lint:
    name: Vala-Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: elementary/actions/vala-lint@master
